// ====== COMPONENTS ======
import { useLocation } from "react-router-dom";

const IshmaelHoustonJonesEssay = (props) => {
    const location = useLocation()
    let background = 'var(--mint-green';
    let textColor = 'black';
    let slash = '/Images/Slash.svg'

    if (location.state) {
        background = location.state.background
        textColor = location.state.textColor
        slash = location.state.slash
    } 
    
    return (
    <>
        <div style={{ backgroundColor: background, color: textColor }} className="essay-padding top-padding flex jc-center mobile-column sand-txt">
            <div className="vault-padding mobile-jc-center mobile-flex">
                <div className="relative essay-title-height mobile-width  flex space-btwn ">
                    <div>
                        <h2 className="subtitle essay-heading">Essay</h2>
                    </div>
                    <img className="essay-slash" src={ slash } />
                    <div className="flex column flex-end">
                        <a href="/ishmael-houston-jones-bio" class="cursor no-underline" style={{ color: textColor}}><h2 className="subtitle essay-author">Ishmael Houston-Jones</h2></a>
                    </div>
                </div>
            </div>
            <section className="flex column al-center mobile-padding">
                <div className="essay-width">
                    <p className="no-top-padding">In 2017, I find myself in my mid-60s and thinking much more about legacy. My own legacy and the legacy of my peers. Sadly, this was provoked by the recent deaths of several of those peers and my meditations led me to contemplate how will their (and my) contributions to this particular and peculiar subset of this art form, experimental dance, be remembered. Who will be able to access the archive of lifetimes of work? How will this archive be available? Formats and gatekeepers, what and who will they be, and do we have any control over either?</p>
                    <p><a id="excerpt-one"></a>The process of my practice seems so fragile and elusive to the idea of archive. My choreography is (almost) never set in the tradition of Modern Dance or Ballet. Therefore, in those infrequent times when I have revived work that was created earlier with a different cast, the new cast is recreating the old work anew. In reality, this is true of the revival of any dance work but this seems much more unambiguous when that work is improvised. Which is “the piece?” What defines a choreography that has no set movement? What are the archival tools available to capture this work? The scattered notes I made in random notebooks hidden away in random drawers and boxes? VHS video tape? Digital transfers? Reviews, previews, and interviews in print or on blogs? Memory?</p>
                    <p>Three different pieces of mine are germane to this discussion. I’ll briefly describe each, its original presentation, and the process by which they were revived years later. And I will question how to best archive and disseminate them.</p>
                    <p>The first piece is the solo DEAD. I made this piece on June 7, 1981, sitting in my living room the night before my 30th birthday. Into a Walkman™ cassette tape recorder, I recited the names of every death I could remember occurring during my lifetime. This took about 10 minutes. On the day of the performance, (actually my birthday party at a friend’s loft in SoHo,) I determined to fall to the floor in some iconic way and rise again before the next name was said by my voice on tape. I, obviously, had never rehearsed this and falling and rising while hearing the haphazard list of names and reacting in some authentic way required much more stamina than I had anticipated. Thus it became a dance of endurance that I performed many more times in New York and on tour. A few years after this I wrote the score for DEAD and my original list for two anthologies: Footnotes: six choreographers inscribe the page and Out of Character: Rants, Raves and Monologues from Today’s Top Performance Artists. In 2010 I agreed to remount, revisit, revive DEAD for Philadelphia Dance Projects. Since the piece required much more energy than I had then and have now, I had to audition a dancer to perform it. But how to revive a piece that came from so much of my own personal lived experiences. The dancer I selected was 23-year-old William Robinson, a recent graduate from University of the Arts. He was born in 1987; all the names on the original list had died before June 1981. Therefore, with the exception of some celebrities, politicians or fictional characters (Marilyn, Golda Meir, Superman), none of my names would resonate with William. Particularly not my relatives, pets and teachers (Aunt Sister, Nugget the First, Miss Kunkel).</p>
                    <p>So the process of “archiving” this work began. I had long lost the original cassette tape on which I recorded the names, but using the written scores I was able to re-record the list and give William insight as to what each name meant to me. It still felt as though the original intent of the piece was to become both physically and emotionally exhausted by the way each name resonated with the dancer during the falling and rising. That dancer was no longer me. So I decided to direct William to generate his own list using mine as an approximate template. Once generated we worked together to edit the list and to determine inflection and pacing in his recording. Did the piece become my piece interpreted by William Robinson? Was it still my choreography? Or did I in fact give DEAD to him and this version was now his? In the future, if someone reads the score in one of the books and performs their version, whose piece is it and to what extent is it the same piece? How should this piece be archived?</p>
                    <p>The second piece I’ll discuss was also created in the 1980s and revived in 2010. The revival of THEM, a collaboration with writer Dennis Cooper, composer/musician Chris Cochrane and me was commissioned by Performance Space 122 and The New Museum. The first draft of THEM was performed at PS 122 in 1985, the full-length premier was the following year. The draft was created with the three authors working closely together with dancer Donald Fleming and actor Jonathan Walker. When the piece premiered in 1986, Jonathan did not perform and Donald was joined by four other male dancers. Chris, Dennis and I always performed live. For the record, the other dancers were Barry Crooks, Julyen Hamilton, Daniel McIntosh, and David Zambrano. I was a member of the ensemble but had one very memorable solo.</p>
                    <p>The piece was composed along three independent but interconnected tracks: dance, music, and text. Chris, Dennis and I were almost always in every rehearsal for both the draft and the premier. We worked autonomously but we also gave one another feedback all along the way. I could comment on and suggest changes in the text, Dennis could recommend sounds for Chris to try, and Chris often had thoughts about the choreography. Again, like most of my work, the choreography is improvised along spatial, emotional, musical and textural structures. And, as with DEAD, the dancers who perform my work have considerable input into what the piece will become. This makes casting, particularly of group work, critical. This brings me to the 2010 revival.</p>
                    <p>Aside from a short overture for me and two other dancers and a solo for me, the dance structures remained largely the same as the original. Chris augmented the sound with some backing tracks and Dennis changed or removed very few words. We held an audition; there had been no audition in 1986. Then, we had invited performers from the “downtown” dance community, particularly from around the Open Movement weekly jam at PS 122. Skill in contact improvisation would be needed and this was true of the revival. But also, Chris, Jonathan and I carefully chose young men who we felt projected a compelling inner life, and would be able to do that onstage. (Dennis had since moved to Paris and was able to come only for the final week of rehearsal and the performances.)</p>
                    <p>Although THEM was made in what was the beginning of the AIDS crisis and the emotional and political tumult surrounding it, there had been no reference to AIDS in the original draft. In the 1986 premier, this was revised by adding what we called amongst ourselves The AIDS Coda. Dennis didn’t write anything specifically new though I did edit, for the finale, a short deconstruction of his opening monologue into fragmented sentences, this was the only text read by one of the dancers and not by Dennis. Chris and I were more direct, though we still wanted to be poetic and to definitely not make an “AIDS piece.” We added two new sections of movement with accompanying sound. In the final tableau five of the dancers stand still in various parts of the stage, staring out toward the audience as if looking in a mirror, tentatively touching the locations of their lymph nodes—neck, underarms and groin—until they are wrestled to the ground by the sixth dancer who has been cast as a figure of violence and/or death. In the scene before that the seventh dancer performs what was my solo in the 80s. He is led blindfolded to a single mattress and is thrown onto it with the carcass of a goat (sometimes sheep) and for a nightmarish 45 seconds wrestles with it and tries to enter its body cavity until he is defeated by it and they are covered by a sheet where they will stay for the remainder of the piece. These are but two examples of what we were asking of our performers. Because we were surrounded by and living with the reality of AIDS every day, in the 1986 version everyone involved understood these references immediately. In the 2010 version Chris and I spent much of the rehearsal time trying to give these young dancers clues to the origins of the emotional landscape of the piece. I believe that on a formal level the 2010 version is “better,” mostly because I was not in the piece except for the brief opening so I could look at the structure and make subtle changes that added clarity and nuance. Also the dancer who does the solo with the animal carcass only appears in the very beginning then during that dance; when I did it I was a member of the ensemble. But I think the raw emotions and meaning of the piece were much more authentic in 1986 than in the newer version. However, because of advances in video technology, the 2010 iteration will be the one that most people will see in the future. Will that be an accurate archive of THEM?</p>
                    <p>The last piece I want to discuss is not my choreography at all although I, along with collaborator Miguel Gutierrez, claim authorship of Variations on Themes from Lost and Found: Scenes from a Life and other works by John Bernd. The choreographer is John Bernd, who died of AIDS complications in 1988 at age 35. He also wrote much of the music heard in the piece, rearranged by Nick Hallett. Miguel and I took excerpts from the seven last pieces John made and fashioned a mash-up that was a unified piece. To quote Miguel, “This piece is not John’s, it’s not ours. It’s something new.”</p>
                    <p>The production of this piece exposes challenges to archiving work. For one of John’s works, Monkey Go West, we could find no video documentation nor reviews. There were photographs and programs that contained some minimal notes by John. That piece is represented in the new piece by very strong images culled from photographs by Dona Ann McAdams. When we could locate it, most of the 1980s era video is quite dismal by today’s iPhone standards. Most are single camera shoots in rehearsals with compromised lighting. I appeared in three of the original pieces so we could use my memories and those of others who were in John’s work—David Alan Harris and Jennifer Monson. Much of John’s print and photographic documentation is housed in the Houghton Library at Harvard University. Fortunately, we had an intern, Janet Werther, who made trips up there and photographed almost everything they had. But most of his video archive is here in the New York Public Library for the Performing Arts at Lincoln Center. We were able to watch whatever they had and most of our dancers went there as well. But there was no way for us to access them in a studio and play them in rehearsal. This was compounded because John didn’t leave a will so the Library’s Legal Department was hesitant to give us copies. There was a quartet in Be Good to Me that I wanted to use but it took so long for us to get a copy that some of the pop music, one tableau, and a short solo danced by Johnny Cruise Mercer wound up being the only parts from Be Good to Me in the 2016 piece. I want to emphasize that the staff of the Dance Department tried very persistently to help us and in the end they did come through but it was a challenging situation.</p>
                    <p>So, do I want just anyone to have access to all of my work? Now? When I’m no longer here? I keep thinking that there is no parallel in writing. One writes a book and anyone can read it if they buy it or it is available in a library or online. Recorded music is much the same? There are a handful of exceptionally good writers writing on the subject of experimental dance. Is there some reason that there aren’t more efficient methods of archiving and disseminating our work to a greater public other than oblivious reviews or by YouTube and Vimeo?</p>
                </div>
            </section>
        </div>
    </>
  );
}

export default IshmaelHoustonJonesEssay;